default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: lottery_development
  username: ivopashov
  password:

test:
  <<: *default
  database: lottery_test
  username: ivopashov
  password:

